### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/sqlite#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [x] Make sure the correct files are all displayed in the editor (#57).
- [x] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by vaeng** [comment]
Testing framework discussion: https://forum.exercism.org/t/creating-a-sqlite3-track/9415/23

**Comment by vaeng** [comment]
Prepare for launch, so we know what has been done.

- [ ] Request track icon
- [ ] Add docs
- [ ] Add exercise docs
- [ ] Add code snippet
- [ ] Update metadata

**Comment by vaeng** [comment]
We shopuld also check all exercises before launch to make sure the correct files are all displayed in the editor.

**Comment by BNAndras** [comment]
Track has launched so I think it's safe to close this now. :)
